plugins {
    id 'io.jmix' version '2.7.3'
    id 'java'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.1.9'
    id 'org.sonarqube' version '7.2.2.6593'
}

apply plugin: 'org.springframework.boot'
apply plugin: 'com.vaadin'

jmix {
    bomVersion = '2.7.3'
    projectId = 'app'
}

group = 'eu.maravelias'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url = 'https://global.repo.jmix.io/repository/public'
    }
}

dependencies {
    implementation 'io.jmix.oidc:jmix-oidc-starter'

    implementation 'io.jmix.core:jmix-core-starter'
    implementation 'io.jmix.data:jmix-eclipselink-starter'
    implementation 'io.jmix.security:jmix-security-starter'
    implementation 'io.jmix.security:jmix-security-flowui-starter'
    implementation 'io.jmix.security:jmix-security-data-starter'
    implementation 'io.jmix.localfs:jmix-localfs-starter'
    implementation 'io.jmix.flowui:jmix-flowui-starter'
    implementation 'io.jmix.flowui:jmix-flowui-data-starter'
    implementation 'io.jmix.flowui:jmix-flowui-themes'
    implementation 'io.jmix.datatools:jmix-datatools-starter'
    implementation 'io.jmix.datatools:jmix-datatools-flowui-starter'

    implementation 'gr.netmechanics.jmix:duration-field-starter:2.3.0'

    implementation 'org.springframework.boot:spring-boot-starter-web'


    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
    testImplementation 'io.jmix.flowui:jmix-flowui-test-assist'
    testRuntimeOnly 'org.hsqldb:hsqldb'
    implementation 'org.postgresql:postgresql'
}

configurations.implementation {
    exclude group: 'com.vaadin', module: 'hilla'
    exclude group: 'com.vaadin', module: 'hilla-dev'
    exclude group: 'com.vaadin', module: 'copilot'
}

test {
    useJUnitPlatform()
}

sonar {
    properties {
        property "sonar.projectKey", "archplan"
        property "sonar.projectName", "ArchitectProjectPlaner"
        property "sonar.host.url", "http://192.168.57.10:9000"
        property "sonar.token", "sqp_655a001f9bd643204ba8cf84fbc1beed1ca259ea"
        property('sonar.cpd.exclusions', ['**/entity/**/*.java'])
    }
}

idea {
    module {
        excludeDirs.addAll(files '.jmix', 'node_modules', 'src/main/frontend/generated/', 'src/main/bundles')
    }
}

vaadin {
    optimizeBundle = false
}
